[versions]
kotlin = "2.3.10"
junit = "4.13.2"
kover = "0.9.4"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
kotlinxKover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
